name: Radicale
version: "3.8.6"
slug: radicale
description: >-
  Radicale is a small but powerful CalDAV (calendars, to-do lists) and
  CardDAV (contacts) server. Supports htpasswd authentication and sharing.
url: "https://radicale.org/"
arch:
  - amd64
  - aarch64
init: false
startup: application
boot: auto
webui: "http://[HOST]:[PORT:5232]"
ports:
  5232/tcp: 5232
ports_description:
  5232/tcp: "Radicale CalDAV/CardDAV server"
map:
  - type: share
    read_only: false
options:
  auth_type: "none"
  storage_folder: "/data/collections"
  log_level: "info"
  sharing: "none"
  bday_summary_template: "Birthday: {name}"
  bday_description_template: "{name} is turning {age}"
  bday_alarm_trigger_template: "PT0S"
  bday_categories: "[]"
  bday_age_max: 0
schema:
  auth_type: "list(none|htpasswd)"
  storage_folder: str
  log_level: "list(debug|info|warning|error|critical)"
  sharing: "list(none|default)"
  bday_summary_template: str
  bday_description_template: str
  bday_alarm_trigger_template: str
  bday_categories: str
  bday_age_max: int
