name: Radicale
version: "3.8.0.0"
slug: radicale
description: >-
  Radicale is a small but powerful CalDAV (calendars, to-do lists) and
  CardDAV (contacts) server. Supports htpasswd authentication.
url: "https://radicale.org/"
arch:
  - amd64
  - aarch64
  - armv7
  - i386
ports:
  5232/tcp: 5232
map:
  - type: share
    read_only: false
    path: /data
boot: auto
watchdog: true
init: true
startup: 5
options:
  RADICALE_CONFIG_AUTH_TYPE: "none"
  RADICALE_CONFIG_AUTH_HTPASSWD_FILENAME: /data/users
  RADICALE_CONFIG_AUTH_HTPASSWD_ENCRYPTION: bcrypt
  RADICALE_CONFIG_STORAGE_FILESYSTEM_FOLDER: /data/collections
  RADICALE_CONFIG_SERVER_HOSTS: 0.0.0.0:5232
schema:
  RADICALE_CONFIG_AUTH_TYPE?: str
  RADICALE_CONFIG_AUTH_HTPASSWD_FILENAME?: str
  RADICALE_CONFIG_AUTH_HTPASSWD_ENCRYPTION?: str
  RADICALE_CONFIG_STORAGE_FILESYSTEM_FOLDER?: str
  RADICALE_CONFIG_SERVER_HOSTS?: str