name: Radicale
version: "3.8.2"
slug: radicale
description: >-
  Radicale is a small but powerful CalDAV (calendars, to-do lists) and
  CardDAV (contacts) server. Supports htpasswd authentication.
url: "https://radicale.org/"
arch:
  - amd64
  - aarch64
init: false
startup: application
boot: auto
webui: "http://[HOST]:[PORT:5232]"
ports:
  5232/tcp: 5232
ports_description:
  5232/tcp: "Radicale CalDAV/CardDAV server"
map:
  - type: share
    read_only: false
options:
  auth_type: "none"
  storage_folder: "/data/collections"
  log_level: "info"
schema:
  auth_type: "list(none|htpasswd)"
  storage_folder: str
  log_level: "list(debug|info|warning|error|critical)"
